server:
  port: 8080

#auto configuration
canopus:
  api:
    gateway:
      endpoints:
        - id: slowApi
          path: /**
          location: lb://canopus-delivery

spring:
  application:
    name: canopus-cloud-gateway

eureka:
  client:
    registerWithEureka: true
    service-url:
      defaultZone: http://canopus-discovery:8761/eureka
